# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_a_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_name',
            field=models.CharField(max_length=50),
        ),
    ]
