# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180526_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(default='Author', max_length=20),
        ),
    ]
