# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repu',
            field=models.IntegerField(default=0),
        ),
    ]
